name: Bug report
description: Create a report to help Termix improve
body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Brief, descriptive title for the PR
      placeholder: "Brief description of the PR"
    validations:
      required: true
